### ISSUE TITLE
Footer fixed to bottom

### ISSUE THREAD

**Issue by Aleniras** [byuweb/2017-components#133] opened 2017-04-10 23:25 UTC
What do we need to do to make this happen?

**Comment by katrialesser** [comment] 2017-04-10 23:47
@Aleniras I don't know what you are meaning here. "Fixed" is a term usually meaning frozen on the page, even as you scroll. That isn't something we've talked about. The footer exists at the end of the page, and always has. Can you clarify?

**Comment by Aleniras** [comment] 2017-04-10 23:49
Yes, sorry. If there is very little content on a page, the footer stays floating in the middle of the window. We need to make it so that even if there is a small amount of content on the page, the footer will be at the bottom of the window.

**Comment by Aleniras** [comment] 2017-04-10 23:49
i.e.  
![image](https://cloud.githubusercontent.com/assets/26605197/24887000/12eebbe4-1e16-11e7-8a13-d161f5ca9059.png)

**Comment by kebowdog** [comment] 2017-04-11 15:22
We've discussed this a few times in our engineering meeting. What you're looking for is usually called a "sticky footer", and it's actually pretty easy to implement with flexbox: https://css-tricks.com/couple-takes-sticky-footer/#article-header-id-3. 

There's nothing stopping this behavior in the components, and you can see an example of it working at  http://lifesciences-new.byu.edu/Info. The problem is that this behavior can't be embedded in the footer component - you have to tell the body tag to expand (or do some other CSS trickery), and that requires knowing how they've structured their HTML. What we can do is make sure the Drupal and Wordpress themes and the demo pages all implement a sticky footer, then include info in the demo pages on how to make it work. I'll update the demo pages now.

**Comment by kebowdog** [comment] 2017-04-12 18:41
I just added some sample code to docs/index.html showing how to do this, so I'm closing this.

**Closed by kebowdog** 2017-04-12 18:41 UTC
